version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      hilt:
        patterns:
          - "com.google.dagger*"
      androidx:
        patterns:
          - "androidx*"
    allow:
      - dependency-name: "com.google.dagger*"
      - dependency-name: "androidx*"
